[project]
name = "repl-nix-exactapprunner"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.52.0",
    "pandas>=2.2.3",
    "pyinstaller>=6.11.0",
    "pyqt6>=6.7.1",
    "requests>=2.32.3",
    "streamlit>=1.39.0",
]
